# Generated by Django 3.0.2 on 2020-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20)),
                ('zipCode', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=30)),
                ('businessType', models.CharField(max_length=200)),
                ('LoanType', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
