# Generated by Django 3.0.2 on 2020-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField(max_length=50000)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
